---
name: Run Scheme on Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Scheme
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: apple/setup-xcode@v2
        with:
          xcode-version: '15.x'

      - name: Build and test
        run: |
          xcodebuild \
            -project EssentialFeed.xcodeproj \
            -scheme CI \
            -destination 'platform=macOS, arch=x86_64' \
            clean build test
